# Generated by Django 3.2.6 on 2021-10-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0002_alter_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(default=None, related_name='students', to='classroom_app.Teacher'),
        ),
    ]
