# Generated by Django 3.2.6 on 2022-03-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_orm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
