# Generated by Django 3.2.6 on 2022-03-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_orm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'age')},
        ),
    ]
