# Generated by Django 3.2.6 on 2022-03-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_orm_app', '0003_alter_person_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CH', 'China'), ('UK', 'United Kingdom'), ('IR', 'Ireland'), ('GER', 'Germany'), ('TR', 'Turkey')], max_length=3),
        ),
    ]
