# Generated by Django 3.2.6 on 2021-08-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='avg_grade',
            field=models.IntegerField(default=0),
        ),
    ]
