# Generated by Django 3.2.6 on 2021-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0002_studentdetail_avg_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='avg_grade',
            field=models.FloatField(default=0),
        ),
    ]
